version: "3.9"

services:
  python:  
    build: .
    environment:
      - PYTHONPATH=/app
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
      - MYSQL_DATABASE=btc
      - MY_API_KEY=${OPENAI_API_KEY}
    container_name: python_week4
    volumes:
      - .:/app
    tty: true
    depends_on:
      - mysql
    networks:
      - btc-network
    ports:
      - "8501:8501"   # Streamlit port

  mysql:
    image: mysql:8.0
    container_name: btc-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: btc
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - btc-network

volumes:
  mysql_data:

networks:
  btc-network:
