name: Build & Deploy to EC2 via Docker Hub

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: kedarvaidya05/bitcoin-app:latest

      # 4. Deploy on EC2
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Create app directory if missing
            mkdir -p /home/ec2-user/app
            chown ec2-user:ec2-user /home/ec2-user/app

      # 5. Copy docker-compose.yml and app code to EC2
      - name: Upload files to EC2
        run: |
          scp -i ${{ secrets.EC2_SSH_KEY }} ./docker-compose.yml ec2-user@${{ secrets.EC2_IP }}:/home/ec2-user/app/
          scp -i ${{ secrets.EC2_SSH_KEY }} -r ./Week4/ ec2-user@${{ secrets.EC2_IP }}:/home/ec2-user/app/Week4/

      # 6. Pull latest image and restart containers on EC2
      - name: Start containers on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/app
            docker-compose pull
            docker-compose down
            docker-compose up -d
