name: Python Template for IDS706

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./Week4/requirements.txt

    - name: Lint with flake8
      run: flake8 ../Week2/Bitcoin_DataAnalysis.py

    - name: Run tests
      run: pytest -vv --cov=Bitcoin_DataAnalysis ../Week3/test_BitcoinDataAnalysis.py


